spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: L337_kampot
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: inventory-service
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

